// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BcAndBankService.proto

// 外挂用 - 综合 bankSDK 和 fabricSDK 调用
// blockchain and bank plugin

package BcAndBankService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamppb.Timestamp

type BcAndBankPayOrderActionRequest struct {
	PayOrder             *UploadChainPayOrder `protobuf:"bytes,1,opt,name=payOrder,proto3" json:"payOrder,omitempty"`
	BankRequest          *BankRequest         `protobuf:"bytes,2,opt,name=bankRequest,proto3" json:"bankRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BcAndBankPayOrderActionRequest) Reset()         { *m = BcAndBankPayOrderActionRequest{} }
func (m *BcAndBankPayOrderActionRequest) String() string { return proto.CompactTextString(m) }
func (*BcAndBankPayOrderActionRequest) ProtoMessage()    {}
func (*BcAndBankPayOrderActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{0}
}

func (m *BcAndBankPayOrderActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcAndBankPayOrderActionRequest.Unmarshal(m, b)
}
func (m *BcAndBankPayOrderActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcAndBankPayOrderActionRequest.Marshal(b, m, deterministic)
}
func (m *BcAndBankPayOrderActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcAndBankPayOrderActionRequest.Merge(m, src)
}
func (m *BcAndBankPayOrderActionRequest) XXX_Size() int {
	return xxx_messageInfo_BcAndBankPayOrderActionRequest.Size(m)
}
func (m *BcAndBankPayOrderActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BcAndBankPayOrderActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BcAndBankPayOrderActionRequest proto.InternalMessageInfo

func (m *BcAndBankPayOrderActionRequest) GetPayOrder() *UploadChainPayOrder {
	if m != nil {
		return m.PayOrder
	}
	return nil
}

func (m *BcAndBankPayOrderActionRequest) GetBankRequest() *BankRequest {
	if m != nil {
		return m.BankRequest
	}
	return nil
}

type BcAndBankFactoringActionRequest struct {
	FactoringOrder       *UploadChainFactoringOrder `protobuf:"bytes,1,opt,name=factoringOrder,proto3" json:"factoringOrder,omitempty"`
	BankRequest          *BankRequest               `protobuf:"bytes,2,opt,name=bankRequest,proto3" json:"bankRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BcAndBankFactoringActionRequest) Reset()         { *m = BcAndBankFactoringActionRequest{} }
func (m *BcAndBankFactoringActionRequest) String() string { return proto.CompactTextString(m) }
func (*BcAndBankFactoringActionRequest) ProtoMessage()    {}
func (*BcAndBankFactoringActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{1}
}

func (m *BcAndBankFactoringActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcAndBankFactoringActionRequest.Unmarshal(m, b)
}
func (m *BcAndBankFactoringActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcAndBankFactoringActionRequest.Marshal(b, m, deterministic)
}
func (m *BcAndBankFactoringActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcAndBankFactoringActionRequest.Merge(m, src)
}
func (m *BcAndBankFactoringActionRequest) XXX_Size() int {
	return xxx_messageInfo_BcAndBankFactoringActionRequest.Size(m)
}
func (m *BcAndBankFactoringActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BcAndBankFactoringActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BcAndBankFactoringActionRequest proto.InternalMessageInfo

func (m *BcAndBankFactoringActionRequest) GetFactoringOrder() *UploadChainFactoringOrder {
	if m != nil {
		return m.FactoringOrder
	}
	return nil
}

func (m *BcAndBankFactoringActionRequest) GetBankRequest() *BankRequest {
	if m != nil {
		return m.BankRequest
	}
	return nil
}

type BcAndBankFactoringRepayActionRequest struct {
	Repay                *UploadChainFactoringOrder `protobuf:"bytes,1,opt,name=repay,proto3" json:"repay,omitempty"`
	BankRequest          *BankRequest               `protobuf:"bytes,2,opt,name=bankRequest,proto3" json:"bankRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BcAndBankFactoringRepayActionRequest) Reset()         { *m = BcAndBankFactoringRepayActionRequest{} }
func (m *BcAndBankFactoringRepayActionRequest) String() string { return proto.CompactTextString(m) }
func (*BcAndBankFactoringRepayActionRequest) ProtoMessage()    {}
func (*BcAndBankFactoringRepayActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{2}
}

func (m *BcAndBankFactoringRepayActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcAndBankFactoringRepayActionRequest.Unmarshal(m, b)
}
func (m *BcAndBankFactoringRepayActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcAndBankFactoringRepayActionRequest.Marshal(b, m, deterministic)
}
func (m *BcAndBankFactoringRepayActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcAndBankFactoringRepayActionRequest.Merge(m, src)
}
func (m *BcAndBankFactoringRepayActionRequest) XXX_Size() int {
	return xxx_messageInfo_BcAndBankFactoringRepayActionRequest.Size(m)
}
func (m *BcAndBankFactoringRepayActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BcAndBankFactoringRepayActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BcAndBankFactoringRepayActionRequest proto.InternalMessageInfo

func (m *BcAndBankFactoringRepayActionRequest) GetRepay() *UploadChainFactoringOrder {
	if m != nil {
		return m.Repay
	}
	return nil
}

func (m *BcAndBankFactoringRepayActionRequest) GetBankRequest() *BankRequest {
	if m != nil {
		return m.BankRequest
	}
	return nil
}

type BcAndBankActionResp struct {
	BcResponse           *BcResponse   `protobuf:"bytes,1,opt,name=bcResponse,proto3" json:"bcResponse,omitempty"`
	BankResponse         *BankResponse `protobuf:"bytes,2,opt,name=bankResponse,proto3" json:"bankResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BcAndBankActionResp) Reset()         { *m = BcAndBankActionResp{} }
func (m *BcAndBankActionResp) String() string { return proto.CompactTextString(m) }
func (*BcAndBankActionResp) ProtoMessage()    {}
func (*BcAndBankActionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{3}
}

func (m *BcAndBankActionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcAndBankActionResp.Unmarshal(m, b)
}
func (m *BcAndBankActionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcAndBankActionResp.Marshal(b, m, deterministic)
}
func (m *BcAndBankActionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcAndBankActionResp.Merge(m, src)
}
func (m *BcAndBankActionResp) XXX_Size() int {
	return xxx_messageInfo_BcAndBankActionResp.Size(m)
}
func (m *BcAndBankActionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BcAndBankActionResp.DiscardUnknown(m)
}

var xxx_messageInfo_BcAndBankActionResp proto.InternalMessageInfo

func (m *BcAndBankActionResp) GetBcResponse() *BcResponse {
	if m != nil {
		return m.BcResponse
	}
	return nil
}

func (m *BcAndBankActionResp) GetBankResponse() *BankResponse {
	if m != nil {
		return m.BankResponse
	}
	return nil
}

// 银行相关参数
// 银行参数基于 XML, 对应的 struct 中有很多标签和无用字段, 使用 xml.Marshal 传 string
type BankRequest struct {
	// 请求头 marshal
	Head string `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// 请求体 marshal
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// 请求方法
	Function             string   `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankRequest) Reset()         { *m = BankRequest{} }
func (m *BankRequest) String() string { return proto.CompactTextString(m) }
func (*BankRequest) ProtoMessage()    {}
func (*BankRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{4}
}

func (m *BankRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankRequest.Unmarshal(m, b)
}
func (m *BankRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankRequest.Marshal(b, m, deterministic)
}
func (m *BankRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankRequest.Merge(m, src)
}
func (m *BankRequest) XXX_Size() int {
	return xxx_messageInfo_BankRequest.Size(m)
}
func (m *BankRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BankRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BankRequest proto.InternalMessageInfo

func (m *BankRequest) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *BankRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *BankRequest) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

// 通用银行信息返回(返回对应结构体 xml marshal)
type BankResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankResponse) Reset()         { *m = BankResponse{} }
func (m *BankResponse) String() string { return proto.CompactTextString(m) }
func (*BankResponse) ProtoMessage()    {}
func (*BankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{5}
}

func (m *BankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankResponse.Unmarshal(m, b)
}
func (m *BankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankResponse.Marshal(b, m, deterministic)
}
func (m *BankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankResponse.Merge(m, src)
}
func (m *BankResponse) XXX_Size() int {
	return xxx_messageInfo_BankResponse.Size(m)
}
func (m *BankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BankResponse proto.InternalMessageInfo

func (m *BankResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// 通用单个上链信息返回(hash)
type BcResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BcResponse) Reset()         { *m = BcResponse{} }
func (m *BcResponse) String() string { return proto.CompactTextString(m) }
func (*BcResponse) ProtoMessage()    {}
func (*BcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{6}
}

func (m *BcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcResponse.Unmarshal(m, b)
}
func (m *BcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcResponse.Marshal(b, m, deterministic)
}
func (m *BcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcResponse.Merge(m, src)
}
func (m *BcResponse) XXX_Size() int {
	return xxx_messageInfo_BcResponse.Size(m)
}
func (m *BcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BcResponse proto.InternalMessageInfo

func (m *BcResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// 通用上链信息返回(hashs)
type BcResponses struct {
	Hash                 []string `protobuf:"bytes,1,rep,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BcResponses) Reset()         { *m = BcResponses{} }
func (m *BcResponses) String() string { return proto.CompactTextString(m) }
func (*BcResponses) ProtoMessage()    {}
func (*BcResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{7}
}

func (m *BcResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcResponses.Unmarshal(m, b)
}
func (m *BcResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcResponses.Marshal(b, m, deterministic)
}
func (m *BcResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcResponses.Merge(m, src)
}
func (m *BcResponses) XXX_Size() int {
	return xxx_messageInfo_BcResponses.Size(m)
}
func (m *BcResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_BcResponses.DiscardUnknown(m)
}

var xxx_messageInfo_BcResponses proto.InternalMessageInfo

func (m *BcResponses) GetHash() []string {
	if m != nil {
		return m.Hash
	}
	return nil
}

// 通用聚合返回(hash, 银行)
type CommonResponse struct {
	BankRsp *BankResponse `protobuf:"bytes,1,opt,name=bankRsp,proto3" json:"bankRsp,omitempty"`
	// 可能会返回多个 hash
	BcRsp                []*BcResponse `protobuf:"bytes,2,rep,name=bcRsp,proto3" json:"bcRsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{8}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetBankRsp() *BankResponse {
	if m != nil {
		return m.BankRsp
	}
	return nil
}

func (m *CommonResponse) GetBcRsp() []*BcResponse {
	if m != nil {
		return m.BcRsp
	}
	return nil
}

type BcAndBankPayOrdersAction struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BcAndBankPayOrdersAction) Reset()         { *m = BcAndBankPayOrdersAction{} }
func (m *BcAndBankPayOrdersAction) String() string { return proto.CompactTextString(m) }
func (*BcAndBankPayOrdersAction) ProtoMessage()    {}
func (*BcAndBankPayOrdersAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{9}
}

func (m *BcAndBankPayOrdersAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcAndBankPayOrdersAction.Unmarshal(m, b)
}
func (m *BcAndBankPayOrdersAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcAndBankPayOrdersAction.Marshal(b, m, deterministic)
}
func (m *BcAndBankPayOrdersAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcAndBankPayOrdersAction.Merge(m, src)
}
func (m *BcAndBankPayOrdersAction) XXX_Size() int {
	return xxx_messageInfo_BcAndBankPayOrdersAction.Size(m)
}
func (m *BcAndBankPayOrdersAction) XXX_DiscardUnknown() {
	xxx_messageInfo_BcAndBankPayOrdersAction.DiscardUnknown(m)
}

var xxx_messageInfo_BcAndBankPayOrdersAction proto.InternalMessageInfo

// dto/UploadChain.go generated
// base -------------- start
type BankAccount struct {
	CardNo               string   `protobuf:"bytes,1,opt,name=cardNo,proto3" json:"cardNo,omitempty"`
	AccountType          string   `protobuf:"bytes,2,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Bank                 string   `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Toibkn               string   `protobuf:"bytes,4,opt,name=toibkn,proto3" json:"toibkn,omitempty"`
	CardOwner            string   `protobuf:"bytes,5,opt,name=cardOwner,proto3" json:"cardOwner,omitempty"`
	ValidStatus          string   `protobuf:"bytes,6,opt,name=validStatus,proto3" json:"validStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankAccount) Reset()         { *m = BankAccount{} }
func (m *BankAccount) String() string { return proto.CompactTextString(m) }
func (*BankAccount) ProtoMessage()    {}
func (*BankAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{10}
}

func (m *BankAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankAccount.Unmarshal(m, b)
}
func (m *BankAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankAccount.Marshal(b, m, deterministic)
}
func (m *BankAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankAccount.Merge(m, src)
}
func (m *BankAccount) XXX_Size() int {
	return xxx_messageInfo_BankAccount.Size(m)
}
func (m *BankAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BankAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BankAccount proto.InternalMessageInfo

func (m *BankAccount) GetCardNo() string {
	if m != nil {
		return m.CardNo
	}
	return ""
}

func (m *BankAccount) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *BankAccount) GetBank() string {
	if m != nil {
		return m.Bank
	}
	return ""
}

func (m *BankAccount) GetToibkn() string {
	if m != nil {
		return m.Toibkn
	}
	return ""
}

func (m *BankAccount) GetCardOwner() string {
	if m != nil {
		return m.CardOwner
	}
	return ""
}

func (m *BankAccount) GetValidStatus() string {
	if m != nil {
		return m.ValidStatus
	}
	return ""
}

type UploadChainType struct {
	LastHash             string   `protobuf:"bytes,1,opt,name=lastHash,proto3" json:"lastHash,omitempty"`
	UploadNode           string   `protobuf:"bytes,2,opt,name=uploadNode,proto3" json:"uploadNode,omitempty"`
	UploaderName         string   `protobuf:"bytes,3,opt,name=uploaderName,proto3" json:"uploaderName,omitempty"`
	UploaderRole         string   `protobuf:"bytes,4,opt,name=uploaderRole,proto3" json:"uploaderRole,omitempty"`
	UploaderRoleName     string   `protobuf:"bytes,5,opt,name=uploaderRoleName,proto3" json:"uploaderRoleName,omitempty"`
	UploaderAccount      string   `protobuf:"bytes,6,opt,name=uploaderAccount,proto3" json:"uploaderAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadChainType) Reset()         { *m = UploadChainType{} }
func (m *UploadChainType) String() string { return proto.CompactTextString(m) }
func (*UploadChainType) ProtoMessage()    {}
func (*UploadChainType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{11}
}

func (m *UploadChainType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainType.Unmarshal(m, b)
}
func (m *UploadChainType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainType.Marshal(b, m, deterministic)
}
func (m *UploadChainType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainType.Merge(m, src)
}
func (m *UploadChainType) XXX_Size() int {
	return xxx_messageInfo_UploadChainType.Size(m)
}
func (m *UploadChainType) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainType.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainType proto.InternalMessageInfo

func (m *UploadChainType) GetLastHash() string {
	if m != nil {
		return m.LastHash
	}
	return ""
}

func (m *UploadChainType) GetUploadNode() string {
	if m != nil {
		return m.UploadNode
	}
	return ""
}

func (m *UploadChainType) GetUploaderName() string {
	if m != nil {
		return m.UploaderName
	}
	return ""
}

func (m *UploadChainType) GetUploaderRole() string {
	if m != nil {
		return m.UploaderRole
	}
	return ""
}

func (m *UploadChainType) GetUploaderRoleName() string {
	if m != nil {
		return m.UploaderRoleName
	}
	return ""
}

func (m *UploadChainType) GetUploaderAccount() string {
	if m != nil {
		return m.UploaderAccount
	}
	return ""
}

type PayOrder struct {
	ShipmentNo           string   `protobuf:"bytes,1,opt,name=shipmentNo,proto3" json:"shipmentNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrder) Reset()         { *m = PayOrder{} }
func (m *PayOrder) String() string { return proto.CompactTextString(m) }
func (*PayOrder) ProtoMessage()    {}
func (*PayOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{12}
}

func (m *PayOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrder.Unmarshal(m, b)
}
func (m *PayOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrder.Marshal(b, m, deterministic)
}
func (m *PayOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrder.Merge(m, src)
}
func (m *PayOrder) XXX_Size() int {
	return xxx_messageInfo_PayOrder.Size(m)
}
func (m *PayOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrder proto.InternalMessageInfo

func (m *PayOrder) GetShipmentNo() string {
	if m != nil {
		return m.ShipmentNo
	}
	return ""
}

type UploadChainCompany struct {
	UploadChainType      *UploadChainType       `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	CompanyName          string                 `protobuf:"bytes,2,opt,name=companyName,proto3" json:"companyName,omitempty"`
	CompanyCode          string                 `protobuf:"bytes,3,opt,name=companyCode,proto3" json:"companyCode,omitempty"`
	ManagerName          string                 `protobuf:"bytes,4,opt,name=managerName,proto3" json:"managerName,omitempty"`
	ManagerPhone         string                 `protobuf:"bytes,5,opt,name=managerPhone,proto3" json:"managerPhone,omitempty"`
	MibCode              string                 `protobuf:"bytes,6,opt,name=mibCode,proto3" json:"mibCode,omitempty"`
	CreditAmount         int64                  `protobuf:"varint,7,opt,name=creditAmount,proto3" json:"creditAmount,omitempty"`
	StartAt              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=endAt,proto3" json:"endAt,omitempty"`
	BankAccount          *BankAccount           `protobuf:"bytes,10,opt,name=bankAccount,proto3" json:"bankAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainCompany) Reset()         { *m = UploadChainCompany{} }
func (m *UploadChainCompany) String() string { return proto.CompactTextString(m) }
func (*UploadChainCompany) ProtoMessage()    {}
func (*UploadChainCompany) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{13}
}

func (m *UploadChainCompany) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainCompany.Unmarshal(m, b)
}
func (m *UploadChainCompany) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainCompany.Marshal(b, m, deterministic)
}
func (m *UploadChainCompany) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainCompany.Merge(m, src)
}
func (m *UploadChainCompany) XXX_Size() int {
	return xxx_messageInfo_UploadChainCompany.Size(m)
}
func (m *UploadChainCompany) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainCompany.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainCompany proto.InternalMessageInfo

func (m *UploadChainCompany) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainCompany) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *UploadChainCompany) GetCompanyCode() string {
	if m != nil {
		return m.CompanyCode
	}
	return ""
}

func (m *UploadChainCompany) GetManagerName() string {
	if m != nil {
		return m.ManagerName
	}
	return ""
}

func (m *UploadChainCompany) GetManagerPhone() string {
	if m != nil {
		return m.ManagerPhone
	}
	return ""
}

func (m *UploadChainCompany) GetMibCode() string {
	if m != nil {
		return m.MibCode
	}
	return ""
}

func (m *UploadChainCompany) GetCreditAmount() int64 {
	if m != nil {
		return m.CreditAmount
	}
	return 0
}

func (m *UploadChainCompany) GetStartAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *UploadChainCompany) GetEndAt() *timestamppb.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

func (m *UploadChainCompany) GetBankAccount() *BankAccount {
	if m != nil {
		return m.BankAccount
	}
	return nil
}

type UploadChainCompanies struct {
	UploadChainCompany   []*UploadChainCompany `protobuf:"bytes,1,rep,name=uploadChainCompany,proto3" json:"uploadChainCompany,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UploadChainCompanies) Reset()         { *m = UploadChainCompanies{} }
func (m *UploadChainCompanies) String() string { return proto.CompactTextString(m) }
func (*UploadChainCompanies) ProtoMessage()    {}
func (*UploadChainCompanies) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{14}
}

func (m *UploadChainCompanies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainCompanies.Unmarshal(m, b)
}
func (m *UploadChainCompanies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainCompanies.Marshal(b, m, deterministic)
}
func (m *UploadChainCompanies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainCompanies.Merge(m, src)
}
func (m *UploadChainCompanies) XXX_Size() int {
	return xxx_messageInfo_UploadChainCompanies.Size(m)
}
func (m *UploadChainCompanies) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainCompanies.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainCompanies proto.InternalMessageInfo

func (m *UploadChainCompanies) GetUploadChainCompany() []*UploadChainCompany {
	if m != nil {
		return m.UploadChainCompany
	}
	return nil
}

type UploadChainConfig struct {
	UploadChainType      *UploadChainType       `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	Key                  string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	TypeOne              string                 `protobuf:"bytes,3,opt,name=typeOne,proto3" json:"typeOne,omitempty"`
	TypeTwo              string                 `protobuf:"bytes,4,opt,name=typeTwo,proto3" json:"typeTwo,omitempty"`
	TypeThree            string                 `protobuf:"bytes,5,opt,name=typeThree,proto3" json:"typeThree,omitempty"`
	Value                string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	StartAt              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt                *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=endAt,proto3" json:"endAt,omitempty"`
	Explain              string                 `protobuf:"bytes,9,opt,name=explain,proto3" json:"explain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainConfig) Reset()         { *m = UploadChainConfig{} }
func (m *UploadChainConfig) String() string { return proto.CompactTextString(m) }
func (*UploadChainConfig) ProtoMessage()    {}
func (*UploadChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{15}
}

func (m *UploadChainConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainConfig.Unmarshal(m, b)
}
func (m *UploadChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainConfig.Marshal(b, m, deterministic)
}
func (m *UploadChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainConfig.Merge(m, src)
}
func (m *UploadChainConfig) XXX_Size() int {
	return xxx_messageInfo_UploadChainConfig.Size(m)
}
func (m *UploadChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainConfig proto.InternalMessageInfo

func (m *UploadChainConfig) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UploadChainConfig) GetTypeOne() string {
	if m != nil {
		return m.TypeOne
	}
	return ""
}

func (m *UploadChainConfig) GetTypeTwo() string {
	if m != nil {
		return m.TypeTwo
	}
	return ""
}

func (m *UploadChainConfig) GetTypeThree() string {
	if m != nil {
		return m.TypeThree
	}
	return ""
}

func (m *UploadChainConfig) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UploadChainConfig) GetStartAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *UploadChainConfig) GetEndAt() *timestamppb.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

func (m *UploadChainConfig) GetExplain() string {
	if m != nil {
		return m.Explain
	}
	return ""
}

type UploadChainConfigs struct {
	UploadChainConfig    []*UploadChainConfig `protobuf:"bytes,1,rep,name=uploadChainConfig,proto3" json:"uploadChainConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UploadChainConfigs) Reset()         { *m = UploadChainConfigs{} }
func (m *UploadChainConfigs) String() string { return proto.CompactTextString(m) }
func (*UploadChainConfigs) ProtoMessage()    {}
func (*UploadChainConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{16}
}

func (m *UploadChainConfigs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainConfigs.Unmarshal(m, b)
}
func (m *UploadChainConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainConfigs.Marshal(b, m, deterministic)
}
func (m *UploadChainConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainConfigs.Merge(m, src)
}
func (m *UploadChainConfigs) XXX_Size() int {
	return xxx_messageInfo_UploadChainConfigs.Size(m)
}
func (m *UploadChainConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainConfigs proto.InternalMessageInfo

func (m *UploadChainConfigs) GetUploadChainConfig() []*UploadChainConfig {
	if m != nil {
		return m.UploadChainConfig
	}
	return nil
}

type UploadChainContract struct {
	UploadChainType      *UploadChainType       `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	ContractNo           string                 `protobuf:"bytes,2,opt,name=contractNo,proto3" json:"contractNo,omitempty"`
	TenderCompany        string                 `protobuf:"bytes,3,opt,name=tenderCompany,proto3" json:"tenderCompany,omitempty"`
	MedicineCode         string                 `protobuf:"bytes,4,opt,name=medicineCode,proto3" json:"medicineCode,omitempty"`
	MedicinePCode        string                 `protobuf:"bytes,5,opt,name=medicinePCode,proto3" json:"medicinePCode,omitempty"`
	CompanyCode          string                 `protobuf:"bytes,6,opt,name=companyCode,proto3" json:"companyCode,omitempty"`
	MibCode              string                 `protobuf:"bytes,7,opt,name=mibCode,proto3" json:"mibCode,omitempty"`
	MedicinePrice        int64                  `protobuf:"varint,8,opt,name=medicinePrice,proto3" json:"medicinePrice,omitempty"`
	TotalAmount          int64                  `protobuf:"varint,9,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	StartAt              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt                *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=endAt,proto3" json:"endAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainContract) Reset()         { *m = UploadChainContract{} }
func (m *UploadChainContract) String() string { return proto.CompactTextString(m) }
func (*UploadChainContract) ProtoMessage()    {}
func (*UploadChainContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{17}
}

func (m *UploadChainContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainContract.Unmarshal(m, b)
}
func (m *UploadChainContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainContract.Marshal(b, m, deterministic)
}
func (m *UploadChainContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainContract.Merge(m, src)
}
func (m *UploadChainContract) XXX_Size() int {
	return xxx_messageInfo_UploadChainContract.Size(m)
}
func (m *UploadChainContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainContract.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainContract proto.InternalMessageInfo

func (m *UploadChainContract) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainContract) GetContractNo() string {
	if m != nil {
		return m.ContractNo
	}
	return ""
}

func (m *UploadChainContract) GetTenderCompany() string {
	if m != nil {
		return m.TenderCompany
	}
	return ""
}

func (m *UploadChainContract) GetMedicineCode() string {
	if m != nil {
		return m.MedicineCode
	}
	return ""
}

func (m *UploadChainContract) GetMedicinePCode() string {
	if m != nil {
		return m.MedicinePCode
	}
	return ""
}

func (m *UploadChainContract) GetCompanyCode() string {
	if m != nil {
		return m.CompanyCode
	}
	return ""
}

func (m *UploadChainContract) GetMibCode() string {
	if m != nil {
		return m.MibCode
	}
	return ""
}

func (m *UploadChainContract) GetMedicinePrice() int64 {
	if m != nil {
		return m.MedicinePrice
	}
	return 0
}

func (m *UploadChainContract) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *UploadChainContract) GetStartAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *UploadChainContract) GetEndAt() *timestamppb.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

type UploadChainContracts struct {
	UploadChainContract  []*UploadChainContract `protobuf:"bytes,1,rep,name=uploadChainContract,proto3" json:"uploadChainContract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainContracts) Reset()         { *m = UploadChainContracts{} }
func (m *UploadChainContracts) String() string { return proto.CompactTextString(m) }
func (*UploadChainContracts) ProtoMessage()    {}
func (*UploadChainContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{18}
}

func (m *UploadChainContracts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainContracts.Unmarshal(m, b)
}
func (m *UploadChainContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainContracts.Marshal(b, m, deterministic)
}
func (m *UploadChainContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainContracts.Merge(m, src)
}
func (m *UploadChainContracts) XXX_Size() int {
	return xxx_messageInfo_UploadChainContracts.Size(m)
}
func (m *UploadChainContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainContracts.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainContracts proto.InternalMessageInfo

func (m *UploadChainContracts) GetUploadChainContract() []*UploadChainContract {
	if m != nil {
		return m.UploadChainContract
	}
	return nil
}

type UploadChainContractMi struct {
	UploadChainType      *UploadChainType `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	ContractNo           string           `protobuf:"bytes,2,opt,name=contractNo,proto3" json:"contractNo,omitempty"`
	MiCode               string           `protobuf:"bytes,3,opt,name=miCode,proto3" json:"miCode,omitempty"`
	MedicineAmount       int64            `protobuf:"varint,4,opt,name=medicineAmount,proto3" json:"medicineAmount,omitempty"`
	ContractMd5          string           `protobuf:"bytes,5,opt,name=contractMd5,proto3" json:"contractMd5,omitempty"`
	ContractUrl          string           `protobuf:"bytes,6,opt,name=contractUrl,proto3" json:"contractUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadChainContractMi) Reset()         { *m = UploadChainContractMi{} }
func (m *UploadChainContractMi) String() string { return proto.CompactTextString(m) }
func (*UploadChainContractMi) ProtoMessage()    {}
func (*UploadChainContractMi) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{19}
}

func (m *UploadChainContractMi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainContractMi.Unmarshal(m, b)
}
func (m *UploadChainContractMi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainContractMi.Marshal(b, m, deterministic)
}
func (m *UploadChainContractMi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainContractMi.Merge(m, src)
}
func (m *UploadChainContractMi) XXX_Size() int {
	return xxx_messageInfo_UploadChainContractMi.Size(m)
}
func (m *UploadChainContractMi) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainContractMi.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainContractMi proto.InternalMessageInfo

func (m *UploadChainContractMi) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainContractMi) GetContractNo() string {
	if m != nil {
		return m.ContractNo
	}
	return ""
}

func (m *UploadChainContractMi) GetMiCode() string {
	if m != nil {
		return m.MiCode
	}
	return ""
}

func (m *UploadChainContractMi) GetMedicineAmount() int64 {
	if m != nil {
		return m.MedicineAmount
	}
	return 0
}

func (m *UploadChainContractMi) GetContractMd5() string {
	if m != nil {
		return m.ContractMd5
	}
	return ""
}

func (m *UploadChainContractMi) GetContractUrl() string {
	if m != nil {
		return m.ContractUrl
	}
	return ""
}

type UploadChainContractMis struct {
	UploadChainContractMi []*UploadChainContractMi `protobuf:"bytes,1,rep,name=uploadChainContractMi,proto3" json:"uploadChainContractMi,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *UploadChainContractMis) Reset()         { *m = UploadChainContractMis{} }
func (m *UploadChainContractMis) String() string { return proto.CompactTextString(m) }
func (*UploadChainContractMis) ProtoMessage()    {}
func (*UploadChainContractMis) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{20}
}

func (m *UploadChainContractMis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainContractMis.Unmarshal(m, b)
}
func (m *UploadChainContractMis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainContractMis.Marshal(b, m, deterministic)
}
func (m *UploadChainContractMis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainContractMis.Merge(m, src)
}
func (m *UploadChainContractMis) XXX_Size() int {
	return xxx_messageInfo_UploadChainContractMis.Size(m)
}
func (m *UploadChainContractMis) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainContractMis.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainContractMis proto.InternalMessageInfo

func (m *UploadChainContractMis) GetUploadChainContractMi() []*UploadChainContractMi {
	if m != nil {
		return m.UploadChainContractMi
	}
	return nil
}

type UploadChainFactoringOrder struct {
	UploadChainType      *UploadChainType       `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	PayOrders            []*PayOrder            `protobuf:"bytes,2,rep,name=payOrders,proto3" json:"payOrders,omitempty"`
	CompanyCode          string                 `protobuf:"bytes,3,opt,name=companyCode,proto3" json:"companyCode,omitempty"`
	FactoringMoney       int64                  `protobuf:"varint,4,opt,name=factoringMoney,proto3" json:"factoringMoney,omitempty"`
	FactoringOrderNo     string                 `protobuf:"bytes,5,opt,name=factoringOrderNo,proto3" json:"factoringOrderNo,omitempty"`
	ApplyDate            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=applyDate,proto3" json:"applyDate,omitempty"`
	ApplyAt              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=applyAt,proto3" json:"applyAt,omitempty"`
	RefundDate           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=refundDate,proto3" json:"refundDate,omitempty"`
	FactoringBankNo      string                 `protobuf:"bytes,9,opt,name=factoringBankNo,proto3" json:"factoringBankNo,omitempty"`
	ActualReceiveMoney   int64                  `protobuf:"varint,10,opt,name=actualReceiveMoney,proto3" json:"actualReceiveMoney,omitempty"`
	FactoringStatus      string                 `protobuf:"bytes,11,opt,name=factoringStatus,proto3" json:"factoringStatus,omitempty"`
	RefundAt             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=refundAt,proto3" json:"refundAt,omitempty"`
	RefundStatus         string                 `protobuf:"bytes,13,opt,name=refundStatus,proto3" json:"refundStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainFactoringOrder) Reset()         { *m = UploadChainFactoringOrder{} }
func (m *UploadChainFactoringOrder) String() string { return proto.CompactTextString(m) }
func (*UploadChainFactoringOrder) ProtoMessage()    {}
func (*UploadChainFactoringOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{21}
}

func (m *UploadChainFactoringOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainFactoringOrder.Unmarshal(m, b)
}
func (m *UploadChainFactoringOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainFactoringOrder.Marshal(b, m, deterministic)
}
func (m *UploadChainFactoringOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainFactoringOrder.Merge(m, src)
}
func (m *UploadChainFactoringOrder) XXX_Size() int {
	return xxx_messageInfo_UploadChainFactoringOrder.Size(m)
}
func (m *UploadChainFactoringOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainFactoringOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainFactoringOrder proto.InternalMessageInfo

func (m *UploadChainFactoringOrder) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainFactoringOrder) GetPayOrders() []*PayOrder {
	if m != nil {
		return m.PayOrders
	}
	return nil
}

func (m *UploadChainFactoringOrder) GetCompanyCode() string {
	if m != nil {
		return m.CompanyCode
	}
	return ""
}

func (m *UploadChainFactoringOrder) GetFactoringMoney() int64 {
	if m != nil {
		return m.FactoringMoney
	}
	return 0
}

func (m *UploadChainFactoringOrder) GetFactoringOrderNo() string {
	if m != nil {
		return m.FactoringOrderNo
	}
	return ""
}

func (m *UploadChainFactoringOrder) GetApplyDate() *timestamppb.Timestamp {
	if m != nil {
		return m.ApplyDate
	}
	return nil
}

func (m *UploadChainFactoringOrder) GetApplyAt() *timestamppb.Timestamp {
	if m != nil {
		return m.ApplyAt
	}
	return nil
}

func (m *UploadChainFactoringOrder) GetRefundDate() *timestamppb.Timestamp {
	if m != nil {
		return m.RefundDate
	}
	return nil
}

func (m *UploadChainFactoringOrder) GetFactoringBankNo() string {
	if m != nil {
		return m.FactoringBankNo
	}
	return ""
}

func (m *UploadChainFactoringOrder) GetActualReceiveMoney() int64 {
	if m != nil {
		return m.ActualReceiveMoney
	}
	return 0
}

func (m *UploadChainFactoringOrder) GetFactoringStatus() string {
	if m != nil {
		return m.FactoringStatus
	}
	return ""
}

func (m *UploadChainFactoringOrder) GetRefundAt() *timestamppb.Timestamp {
	if m != nil {
		return m.RefundAt
	}
	return nil
}

func (m *UploadChainFactoringOrder) GetRefundStatus() string {
	if m != nil {
		return m.RefundStatus
	}
	return ""
}

type UploadChainFactoringOrders struct {
	UploadChainFactoringOrder []*UploadChainFactoringOrder `protobuf:"bytes,1,rep,name=uploadChainFactoringOrder,proto3" json:"uploadChainFactoringOrder,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                     `json:"-"`
	XXX_unrecognized          []byte                       `json:"-"`
	XXX_sizecache             int32                        `json:"-"`
}

func (m *UploadChainFactoringOrders) Reset()         { *m = UploadChainFactoringOrders{} }
func (m *UploadChainFactoringOrders) String() string { return proto.CompactTextString(m) }
func (*UploadChainFactoringOrders) ProtoMessage()    {}
func (*UploadChainFactoringOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{22}
}

func (m *UploadChainFactoringOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainFactoringOrders.Unmarshal(m, b)
}
func (m *UploadChainFactoringOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainFactoringOrders.Marshal(b, m, deterministic)
}
func (m *UploadChainFactoringOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainFactoringOrders.Merge(m, src)
}
func (m *UploadChainFactoringOrders) XXX_Size() int {
	return xxx_messageInfo_UploadChainFactoringOrders.Size(m)
}
func (m *UploadChainFactoringOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainFactoringOrders.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainFactoringOrders proto.InternalMessageInfo

func (m *UploadChainFactoringOrders) GetUploadChainFactoringOrder() []*UploadChainFactoringOrder {
	if m != nil {
		return m.UploadChainFactoringOrder
	}
	return nil
}

type UploadChainMedicine struct {
	UploadChainType       *UploadChainType `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	MedicineName          string           `protobuf:"bytes,2,opt,name=medicineName,proto3" json:"medicineName,omitempty"`
	MedicineCode          string           `protobuf:"bytes,3,opt,name=medicineCode,proto3" json:"medicineCode,omitempty"`
	MedicinePCode         string           `protobuf:"bytes,4,opt,name=medicinePCode,proto3" json:"medicinePCode,omitempty"`
	MedicineSpecification string           `protobuf:"bytes,5,opt,name=medicineSpecification,proto3" json:"medicineSpecification,omitempty"`
	MedicineForm          string           `protobuf:"bytes,6,opt,name=medicineForm,proto3" json:"medicineForm,omitempty"`
	MedicinePackage       string           `protobuf:"bytes,7,opt,name=medicinePackage,proto3" json:"medicinePackage,omitempty"`
	MedicineUnit          string           `protobuf:"bytes,8,opt,name=medicineUnit,proto3" json:"medicineUnit,omitempty"`
	CalculateRate         int64            `protobuf:"varint,9,opt,name=calculateRate,proto3" json:"calculateRate,omitempty"`
	Manufacturer          string           `protobuf:"bytes,10,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *UploadChainMedicine) Reset()         { *m = UploadChainMedicine{} }
func (m *UploadChainMedicine) String() string { return proto.CompactTextString(m) }
func (*UploadChainMedicine) ProtoMessage()    {}
func (*UploadChainMedicine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{23}
}

func (m *UploadChainMedicine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainMedicine.Unmarshal(m, b)
}
func (m *UploadChainMedicine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainMedicine.Marshal(b, m, deterministic)
}
func (m *UploadChainMedicine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainMedicine.Merge(m, src)
}
func (m *UploadChainMedicine) XXX_Size() int {
	return xxx_messageInfo_UploadChainMedicine.Size(m)
}
func (m *UploadChainMedicine) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainMedicine.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainMedicine proto.InternalMessageInfo

func (m *UploadChainMedicine) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainMedicine) GetMedicineName() string {
	if m != nil {
		return m.MedicineName
	}
	return ""
}

func (m *UploadChainMedicine) GetMedicineCode() string {
	if m != nil {
		return m.MedicineCode
	}
	return ""
}

func (m *UploadChainMedicine) GetMedicinePCode() string {
	if m != nil {
		return m.MedicinePCode
	}
	return ""
}

func (m *UploadChainMedicine) GetMedicineSpecification() string {
	if m != nil {
		return m.MedicineSpecification
	}
	return ""
}

func (m *UploadChainMedicine) GetMedicineForm() string {
	if m != nil {
		return m.MedicineForm
	}
	return ""
}

func (m *UploadChainMedicine) GetMedicinePackage() string {
	if m != nil {
		return m.MedicinePackage
	}
	return ""
}

func (m *UploadChainMedicine) GetMedicineUnit() string {
	if m != nil {
		return m.MedicineUnit
	}
	return ""
}

func (m *UploadChainMedicine) GetCalculateRate() int64 {
	if m != nil {
		return m.CalculateRate
	}
	return 0
}

func (m *UploadChainMedicine) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

type UploadChainMedicines struct {
	UploadChainMedicine  []*UploadChainMedicine `protobuf:"bytes,1,rep,name=uploadChainMedicine,proto3" json:"uploadChainMedicine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainMedicines) Reset()         { *m = UploadChainMedicines{} }
func (m *UploadChainMedicines) String() string { return proto.CompactTextString(m) }
func (*UploadChainMedicines) ProtoMessage()    {}
func (*UploadChainMedicines) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{24}
}

func (m *UploadChainMedicines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainMedicines.Unmarshal(m, b)
}
func (m *UploadChainMedicines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainMedicines.Marshal(b, m, deterministic)
}
func (m *UploadChainMedicines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainMedicines.Merge(m, src)
}
func (m *UploadChainMedicines) XXX_Size() int {
	return xxx_messageInfo_UploadChainMedicines.Size(m)
}
func (m *UploadChainMedicines) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainMedicines.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainMedicines proto.InternalMessageInfo

func (m *UploadChainMedicines) GetUploadChainMedicine() []*UploadChainMedicine {
	if m != nil {
		return m.UploadChainMedicine
	}
	return nil
}

type UploadChainMi struct {
	UploadChainType      *UploadChainType `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	MibCode              string           `protobuf:"bytes,2,opt,name=mibCode,proto3" json:"mibCode,omitempty"`
	MiName               string           `protobuf:"bytes,3,opt,name=miName,proto3" json:"miName,omitempty"`
	MiCode               string           `protobuf:"bytes,4,opt,name=miCode,proto3" json:"miCode,omitempty"`
	MiType               string           `protobuf:"bytes,5,opt,name=miType,proto3" json:"miType,omitempty"`
	ManagerName          string           `protobuf:"bytes,6,opt,name=managerName,proto3" json:"managerName,omitempty"`
	ManagerPhone         string           `protobuf:"bytes,7,opt,name=managerPhone,proto3" json:"managerPhone,omitempty"`
	LimitBalance         int64            `protobuf:"varint,8,opt,name=limitBalance,proto3" json:"limitBalance,omitempty"`
	SpecialAccount       *BankAccount     `protobuf:"bytes,9,opt,name=specialAccount,proto3" json:"specialAccount,omitempty"`
	NormalAccount        *BankAccount     `protobuf:"bytes,10,opt,name=normalAccount,proto3" json:"normalAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadChainMi) Reset()         { *m = UploadChainMi{} }
func (m *UploadChainMi) String() string { return proto.CompactTextString(m) }
func (*UploadChainMi) ProtoMessage()    {}
func (*UploadChainMi) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{25}
}

func (m *UploadChainMi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainMi.Unmarshal(m, b)
}
func (m *UploadChainMi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainMi.Marshal(b, m, deterministic)
}
func (m *UploadChainMi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainMi.Merge(m, src)
}
func (m *UploadChainMi) XXX_Size() int {
	return xxx_messageInfo_UploadChainMi.Size(m)
}
func (m *UploadChainMi) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainMi.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainMi proto.InternalMessageInfo

func (m *UploadChainMi) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainMi) GetMibCode() string {
	if m != nil {
		return m.MibCode
	}
	return ""
}

func (m *UploadChainMi) GetMiName() string {
	if m != nil {
		return m.MiName
	}
	return ""
}

func (m *UploadChainMi) GetMiCode() string {
	if m != nil {
		return m.MiCode
	}
	return ""
}

func (m *UploadChainMi) GetMiType() string {
	if m != nil {
		return m.MiType
	}
	return ""
}

func (m *UploadChainMi) GetManagerName() string {
	if m != nil {
		return m.ManagerName
	}
	return ""
}

func (m *UploadChainMi) GetManagerPhone() string {
	if m != nil {
		return m.ManagerPhone
	}
	return ""
}

func (m *UploadChainMi) GetLimitBalance() int64 {
	if m != nil {
		return m.LimitBalance
	}
	return 0
}

func (m *UploadChainMi) GetSpecialAccount() *BankAccount {
	if m != nil {
		return m.SpecialAccount
	}
	return nil
}

func (m *UploadChainMi) GetNormalAccount() *BankAccount {
	if m != nil {
		return m.NormalAccount
	}
	return nil
}

type UploadChainMis struct {
	UploadChainMi        []*UploadChainMi `protobuf:"bytes,1,rep,name=uploadChainMi,proto3" json:"uploadChainMi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadChainMis) Reset()         { *m = UploadChainMis{} }
func (m *UploadChainMis) String() string { return proto.CompactTextString(m) }
func (*UploadChainMis) ProtoMessage()    {}
func (*UploadChainMis) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{26}
}

func (m *UploadChainMis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainMis.Unmarshal(m, b)
}
func (m *UploadChainMis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainMis.Marshal(b, m, deterministic)
}
func (m *UploadChainMis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainMis.Merge(m, src)
}
func (m *UploadChainMis) XXX_Size() int {
	return xxx_messageInfo_UploadChainMis.Size(m)
}
func (m *UploadChainMis) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainMis.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainMis proto.InternalMessageInfo

func (m *UploadChainMis) GetUploadChainMi() []*UploadChainMi {
	if m != nil {
		return m.UploadChainMi
	}
	return nil
}

type UploadChainPayOrder struct {
	UploadChainType      *UploadChainType       `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	ShipmentNo           string                 `protobuf:"bytes,2,opt,name=shipmentNo,proto3" json:"shipmentNo,omitempty"`
	OrderAmount          int64                  `protobuf:"varint,3,opt,name=orderAmount,proto3" json:"orderAmount,omitempty"`
	MiCode               string                 `protobuf:"bytes,4,opt,name=miCode,proto3" json:"miCode,omitempty"`
	CompanyCode          string                 `protobuf:"bytes,5,opt,name=companyCode,proto3" json:"companyCode,omitempty"`
	OutTradeNo           string                 `protobuf:"bytes,6,opt,name=outTradeNo,proto3" json:"outTradeNo,omitempty"`
	PayType              string                 `protobuf:"bytes,7,opt,name=payType,proto3" json:"payType,omitempty"`
	PayAt                *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=payAt,proto3" json:"payAt,omitempty"`
	PayStatus            string                 `protobuf:"bytes,9,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	FactoringStatus      string                 `protobuf:"bytes,10,opt,name=factoringStatus,proto3" json:"factoringStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainPayOrder) Reset()         { *m = UploadChainPayOrder{} }
func (m *UploadChainPayOrder) String() string { return proto.CompactTextString(m) }
func (*UploadChainPayOrder) ProtoMessage()    {}
func (*UploadChainPayOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{27}
}

func (m *UploadChainPayOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainPayOrder.Unmarshal(m, b)
}
func (m *UploadChainPayOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainPayOrder.Marshal(b, m, deterministic)
}
func (m *UploadChainPayOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainPayOrder.Merge(m, src)
}
func (m *UploadChainPayOrder) XXX_Size() int {
	return xxx_messageInfo_UploadChainPayOrder.Size(m)
}
func (m *UploadChainPayOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainPayOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainPayOrder proto.InternalMessageInfo

func (m *UploadChainPayOrder) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainPayOrder) GetShipmentNo() string {
	if m != nil {
		return m.ShipmentNo
	}
	return ""
}

func (m *UploadChainPayOrder) GetOrderAmount() int64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *UploadChainPayOrder) GetMiCode() string {
	if m != nil {
		return m.MiCode
	}
	return ""
}

func (m *UploadChainPayOrder) GetCompanyCode() string {
	if m != nil {
		return m.CompanyCode
	}
	return ""
}

func (m *UploadChainPayOrder) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *UploadChainPayOrder) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *UploadChainPayOrder) GetPayAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PayAt
	}
	return nil
}

func (m *UploadChainPayOrder) GetPayStatus() string {
	if m != nil {
		return m.PayStatus
	}
	return ""
}

func (m *UploadChainPayOrder) GetFactoringStatus() string {
	if m != nil {
		return m.FactoringStatus
	}
	return ""
}

type UploadChainPayOrders struct {
	UploadChainPayOrder  []*UploadChainPayOrder `protobuf:"bytes,1,rep,name=uploadChainPayOrder,proto3" json:"uploadChainPayOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainPayOrders) Reset()         { *m = UploadChainPayOrders{} }
func (m *UploadChainPayOrders) String() string { return proto.CompactTextString(m) }
func (*UploadChainPayOrders) ProtoMessage()    {}
func (*UploadChainPayOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{28}
}

func (m *UploadChainPayOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainPayOrders.Unmarshal(m, b)
}
func (m *UploadChainPayOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainPayOrders.Marshal(b, m, deterministic)
}
func (m *UploadChainPayOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainPayOrders.Merge(m, src)
}
func (m *UploadChainPayOrders) XXX_Size() int {
	return xxx_messageInfo_UploadChainPayOrders.Size(m)
}
func (m *UploadChainPayOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainPayOrders.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainPayOrders proto.InternalMessageInfo

func (m *UploadChainPayOrders) GetUploadChainPayOrder() []*UploadChainPayOrder {
	if m != nil {
		return m.UploadChainPayOrder
	}
	return nil
}

type UploadChainShipment struct {
	UploadChainType      *UploadChainType       `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	TpOrderNo            string                 `protobuf:"bytes,2,opt,name=tpOrderNo,proto3" json:"tpOrderNo,omitempty"`
	OrderNo              string                 `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	TpCode               string                 `protobuf:"bytes,4,opt,name=tpCode,proto3" json:"tpCode,omitempty"`
	MibCode              string                 `protobuf:"bytes,5,opt,name=mibCode,proto3" json:"mibCode,omitempty"`
	ShipmentAmount       int64                  `protobuf:"varint,6,opt,name=shipmentAmount,proto3" json:"shipmentAmount,omitempty"`
	OrderAmount          int64                  `protobuf:"varint,7,opt,name=orderAmount,proto3" json:"orderAmount,omitempty"`
	ContractNo           string                 `protobuf:"bytes,8,opt,name=contractNo,proto3" json:"contractNo,omitempty"`
	MiCode               string                 `protobuf:"bytes,9,opt,name=miCode,proto3" json:"miCode,omitempty"`
	MedicineCode         string                 `protobuf:"bytes,10,opt,name=medicineCode,proto3" json:"medicineCode,omitempty"`
	MedicinePCode        string                 `protobuf:"bytes,11,opt,name=medicinePCode,proto3" json:"medicinePCode,omitempty"`
	CompanyCode          string                 `protobuf:"bytes,12,opt,name=companyCode,proto3" json:"companyCode,omitempty"`
	SyncAt               *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=syncAt,proto3" json:"syncAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainShipment) Reset()         { *m = UploadChainShipment{} }
func (m *UploadChainShipment) String() string { return proto.CompactTextString(m) }
func (*UploadChainShipment) ProtoMessage()    {}
func (*UploadChainShipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{29}
}

func (m *UploadChainShipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainShipment.Unmarshal(m, b)
}
func (m *UploadChainShipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainShipment.Marshal(b, m, deterministic)
}
func (m *UploadChainShipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainShipment.Merge(m, src)
}
func (m *UploadChainShipment) XXX_Size() int {
	return xxx_messageInfo_UploadChainShipment.Size(m)
}
func (m *UploadChainShipment) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainShipment.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainShipment proto.InternalMessageInfo

func (m *UploadChainShipment) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainShipment) GetTpOrderNo() string {
	if m != nil {
		return m.TpOrderNo
	}
	return ""
}

func (m *UploadChainShipment) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *UploadChainShipment) GetTpCode() string {
	if m != nil {
		return m.TpCode
	}
	return ""
}

func (m *UploadChainShipment) GetMibCode() string {
	if m != nil {
		return m.MibCode
	}
	return ""
}

func (m *UploadChainShipment) GetShipmentAmount() int64 {
	if m != nil {
		return m.ShipmentAmount
	}
	return 0
}

func (m *UploadChainShipment) GetOrderAmount() int64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *UploadChainShipment) GetContractNo() string {
	if m != nil {
		return m.ContractNo
	}
	return ""
}

func (m *UploadChainShipment) GetMiCode() string {
	if m != nil {
		return m.MiCode
	}
	return ""
}

func (m *UploadChainShipment) GetMedicineCode() string {
	if m != nil {
		return m.MedicineCode
	}
	return ""
}

func (m *UploadChainShipment) GetMedicinePCode() string {
	if m != nil {
		return m.MedicinePCode
	}
	return ""
}

func (m *UploadChainShipment) GetCompanyCode() string {
	if m != nil {
		return m.CompanyCode
	}
	return ""
}

func (m *UploadChainShipment) GetSyncAt() *timestamppb.Timestamp {
	if m != nil {
		return m.SyncAt
	}
	return nil
}

type UploadChainShipments struct {
	UploadChainShipment  []*UploadChainShipment `protobuf:"bytes,1,rep,name=uploadChainShipment,proto3" json:"uploadChainShipment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainShipments) Reset()         { *m = UploadChainShipments{} }
func (m *UploadChainShipments) String() string { return proto.CompactTextString(m) }
func (*UploadChainShipments) ProtoMessage()    {}
func (*UploadChainShipments) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{30}
}

func (m *UploadChainShipments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainShipments.Unmarshal(m, b)
}
func (m *UploadChainShipments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainShipments.Marshal(b, m, deterministic)
}
func (m *UploadChainShipments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainShipments.Merge(m, src)
}
func (m *UploadChainShipments) XXX_Size() int {
	return xxx_messageInfo_UploadChainShipments.Size(m)
}
func (m *UploadChainShipments) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainShipments.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainShipments proto.InternalMessageInfo

func (m *UploadChainShipments) GetUploadChainShipment() []*UploadChainShipment {
	if m != nil {
		return m.UploadChainShipment
	}
	return nil
}

type UploadChainShipmentOrder struct {
	UploadChainType      *UploadChainType       `protobuf:"bytes,1,opt,name=uploadChainType,proto3" json:"uploadChainType,omitempty"`
	Plans                []*UploadChainShipment `protobuf:"bytes,2,rep,name=plans,proto3" json:"plans,omitempty"`
	ShipmentNo           string                 `protobuf:"bytes,3,opt,name=shipmentNo,proto3" json:"shipmentNo,omitempty"`
	InvoiceMd5           string                 `protobuf:"bytes,4,opt,name=invoiceMd5,proto3" json:"invoiceMd5,omitempty"`
	InvoiceUrl           string                 `protobuf:"bytes,5,opt,name=invoiceUrl,proto3" json:"invoiceUrl,omitempty"`
	InvoiceType          string                 `protobuf:"bytes,6,opt,name=invoiceType,proto3" json:"invoiceType,omitempty"`
	InvoiceTotal         int64                  `protobuf:"varint,7,opt,name=invoiceTotal,proto3" json:"invoiceTotal,omitempty"`
	InvoiceTax           int64                  `protobuf:"varint,8,opt,name=invoiceTax,proto3" json:"invoiceTax,omitempty"`
	InvoiceCheckCode     string                 `protobuf:"bytes,9,opt,name=invoiceCheckCode,proto3" json:"invoiceCheckCode,omitempty"`
	InvoiceNo            string                 `protobuf:"bytes,10,opt,name=invoiceNo,proto3" json:"invoiceNo,omitempty"`
	InvoiceCode          string                 `protobuf:"bytes,11,opt,name=invoiceCode,proto3" json:"invoiceCode,omitempty"`
	InvoiceDate          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=invoiceDate,proto3" json:"invoiceDate,omitempty"`
	SendOutAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=sendOutAt,proto3" json:"sendOutAt,omitempty"`
	ShipmentCode         string                 `protobuf:"bytes,14,opt,name=shipmentCode,proto3" json:"shipmentCode,omitempty"`
	ShipmentCompany      string                 `protobuf:"bytes,15,opt,name=shipmentCompany,proto3" json:"shipmentCompany,omitempty"`
	ShipmentStatus       string                 `protobuf:"bytes,16,opt,name=shipmentStatus,proto3" json:"shipmentStatus,omitempty"`
	ReceiveAt            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=receiveAt,proto3" json:"receiveAt,omitempty"`
	ConfirmAt            *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=confirmAt,proto3" json:"confirmAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UploadChainShipmentOrder) Reset()         { *m = UploadChainShipmentOrder{} }
func (m *UploadChainShipmentOrder) String() string { return proto.CompactTextString(m) }
func (*UploadChainShipmentOrder) ProtoMessage()    {}
func (*UploadChainShipmentOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{31}
}

func (m *UploadChainShipmentOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainShipmentOrder.Unmarshal(m, b)
}
func (m *UploadChainShipmentOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainShipmentOrder.Marshal(b, m, deterministic)
}
func (m *UploadChainShipmentOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainShipmentOrder.Merge(m, src)
}
func (m *UploadChainShipmentOrder) XXX_Size() int {
	return xxx_messageInfo_UploadChainShipmentOrder.Size(m)
}
func (m *UploadChainShipmentOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainShipmentOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainShipmentOrder proto.InternalMessageInfo

func (m *UploadChainShipmentOrder) GetUploadChainType() *UploadChainType {
	if m != nil {
		return m.UploadChainType
	}
	return nil
}

func (m *UploadChainShipmentOrder) GetPlans() []*UploadChainShipment {
	if m != nil {
		return m.Plans
	}
	return nil
}

func (m *UploadChainShipmentOrder) GetShipmentNo() string {
	if m != nil {
		return m.ShipmentNo
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetInvoiceMd5() string {
	if m != nil {
		return m.InvoiceMd5
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetInvoiceUrl() string {
	if m != nil {
		return m.InvoiceUrl
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetInvoiceType() string {
	if m != nil {
		return m.InvoiceType
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetInvoiceTotal() int64 {
	if m != nil {
		return m.InvoiceTotal
	}
	return 0
}

func (m *UploadChainShipmentOrder) GetInvoiceTax() int64 {
	if m != nil {
		return m.InvoiceTax
	}
	return 0
}

func (m *UploadChainShipmentOrder) GetInvoiceCheckCode() string {
	if m != nil {
		return m.InvoiceCheckCode
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetInvoiceNo() string {
	if m != nil {
		return m.InvoiceNo
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetInvoiceCode() string {
	if m != nil {
		return m.InvoiceCode
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetInvoiceDate() *timestamppb.Timestamp {
	if m != nil {
		return m.InvoiceDate
	}
	return nil
}

func (m *UploadChainShipmentOrder) GetSendOutAt() *timestamppb.Timestamp {
	if m != nil {
		return m.SendOutAt
	}
	return nil
}

func (m *UploadChainShipmentOrder) GetShipmentCode() string {
	if m != nil {
		return m.ShipmentCode
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetShipmentCompany() string {
	if m != nil {
		return m.ShipmentCompany
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetShipmentStatus() string {
	if m != nil {
		return m.ShipmentStatus
	}
	return ""
}

func (m *UploadChainShipmentOrder) GetReceiveAt() *timestamppb.Timestamp {
	if m != nil {
		return m.ReceiveAt
	}
	return nil
}

func (m *UploadChainShipmentOrder) GetConfirmAt() *timestamppb.Timestamp {
	if m != nil {
		return m.ConfirmAt
	}
	return nil
}

type UploadChainShipmentOrders struct {
	UploadChainShipmentOrder []*UploadChainShipmentOrder `protobuf:"bytes,1,rep,name=uploadChainShipmentOrder,proto3" json:"uploadChainShipmentOrder,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *UploadChainShipmentOrders) Reset()         { *m = UploadChainShipmentOrders{} }
func (m *UploadChainShipmentOrders) String() string { return proto.CompactTextString(m) }
func (*UploadChainShipmentOrders) ProtoMessage()    {}
func (*UploadChainShipmentOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0de6912b10a8a15, []int{32}
}

func (m *UploadChainShipmentOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChainShipmentOrders.Unmarshal(m, b)
}
func (m *UploadChainShipmentOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChainShipmentOrders.Marshal(b, m, deterministic)
}
func (m *UploadChainShipmentOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChainShipmentOrders.Merge(m, src)
}
func (m *UploadChainShipmentOrders) XXX_Size() int {
	return xxx_messageInfo_UploadChainShipmentOrders.Size(m)
}
func (m *UploadChainShipmentOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChainShipmentOrders.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChainShipmentOrders proto.InternalMessageInfo

func (m *UploadChainShipmentOrders) GetUploadChainShipmentOrder() []*UploadChainShipmentOrder {
	if m != nil {
		return m.UploadChainShipmentOrder
	}
	return nil
}

func init() {
	proto.RegisterType((*BcAndBankPayOrderActionRequest)(nil), "BcAndBankService.BcAndBankPayOrderActionRequest")
	proto.RegisterType((*BcAndBankFactoringActionRequest)(nil), "BcAndBankService.BcAndBankFactoringActionRequest")
	proto.RegisterType((*BcAndBankFactoringRepayActionRequest)(nil), "BcAndBankService.BcAndBankFactoringRepayActionRequest")
	proto.RegisterType((*BcAndBankActionResp)(nil), "BcAndBankService.BcAndBankActionResp")
	proto.RegisterType((*BankRequest)(nil), "BcAndBankService.BankRequest")
	proto.RegisterType((*BankResponse)(nil), "BcAndBankService.BankResponse")
	proto.RegisterType((*BcResponse)(nil), "BcAndBankService.BcResponse")
	proto.RegisterType((*BcResponses)(nil), "BcAndBankService.BcResponses")
	proto.RegisterType((*CommonResponse)(nil), "BcAndBankService.CommonResponse")
	proto.RegisterType((*BcAndBankPayOrdersAction)(nil), "BcAndBankService.BcAndBankPayOrdersAction")
	proto.RegisterType((*BankAccount)(nil), "BcAndBankService.BankAccount")
	proto.RegisterType((*UploadChainType)(nil), "BcAndBankService.UploadChainType")
	proto.RegisterType((*PayOrder)(nil), "BcAndBankService.PayOrder")
	proto.RegisterType((*UploadChainCompany)(nil), "BcAndBankService.UploadChainCompany")
	proto.RegisterType((*UploadChainCompanies)(nil), "BcAndBankService.UploadChainCompanies")
	proto.RegisterType((*UploadChainConfig)(nil), "BcAndBankService.UploadChainConfig")
	proto.RegisterType((*UploadChainConfigs)(nil), "BcAndBankService.UploadChainConfigs")
	proto.RegisterType((*UploadChainContract)(nil), "BcAndBankService.UploadChainContract")
	proto.RegisterType((*UploadChainContracts)(nil), "BcAndBankService.UploadChainContracts")
	proto.RegisterType((*UploadChainContractMi)(nil), "BcAndBankService.UploadChainContractMi")
	proto.RegisterType((*UploadChainContractMis)(nil), "BcAndBankService.UploadChainContractMis")
	proto.RegisterType((*UploadChainFactoringOrder)(nil), "BcAndBankService.UploadChainFactoringOrder")
	proto.RegisterType((*UploadChainFactoringOrders)(nil), "BcAndBankService.UploadChainFactoringOrders")
	proto.RegisterType((*UploadChainMedicine)(nil), "BcAndBankService.UploadChainMedicine")
	proto.RegisterType((*UploadChainMedicines)(nil), "BcAndBankService.UploadChainMedicines")
	proto.RegisterType((*UploadChainMi)(nil), "BcAndBankService.UploadChainMi")
	proto.RegisterType((*UploadChainMis)(nil), "BcAndBankService.UploadChainMis")
	proto.RegisterType((*UploadChainPayOrder)(nil), "BcAndBankService.UploadChainPayOrder")
	proto.RegisterType((*UploadChainPayOrders)(nil), "BcAndBankService.UploadChainPayOrders")
	proto.RegisterType((*UploadChainShipment)(nil), "BcAndBankService.UploadChainShipment")
	proto.RegisterType((*UploadChainShipments)(nil), "BcAndBankService.UploadChainShipments")
	proto.RegisterType((*UploadChainShipmentOrder)(nil), "BcAndBankService.UploadChainShipmentOrder")
	proto.RegisterType((*UploadChainShipmentOrders)(nil), "BcAndBankService.UploadChainShipmentOrders")
}

func init() {
	proto.RegisterFile("BcAndBankService.proto", fileDescriptor_c0de6912b10a8a15)
}

var fileDescriptor_c0de6912b10a8a15 = []byte{
	// 2145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x5a, 0x4f, 0x6f, 0x1c, 0x49,
	0x15, 0x67, 0x3c, 0x99, 0x19, 0xcf, 0x1b, 0xdb, 0x49, 0x2a, 0x1b, 0x33, 0x3b, 0x6c, 0x1c, 0x6f,
	0x93, 0x98, 0x90, 0x20, 0x67, 0x31, 0xcb, 0x6a, 0xc5, 0xae, 0x84, 0xc6, 0x66, 0x23, 0x24, 0x94,
	0x89, 0xb7, 0xed, 0xb0, 0xd2, 0x4a, 0x80, 0xca, 0x3d, 0x65, 0xbb, 0xe5, 0x9e, 0xae, 0xa6, 0xff,
	0x38, 0x3b, 0x1c, 0xf6, 0xc2, 0x01, 0xce, 0x5c, 0xf8, 0x02, 0x7b, 0xe2, 0x0a, 0x12, 0x9c, 0xf9,
	0x08, 0x9c, 0x11, 0x5f, 0x00, 0x89, 0x13, 0x1f, 0x00, 0xd5, 0xbf, 0xee, 0xaa, 0xea, 0x9e, 0xe9,
	0x76, 0xd6, 0xe1, 0xd6, 0xf5, 0xab, 0x57, 0xaf, 0x5e, 0xbd, 0xf7, 0xea, 0xfd, 0xa9, 0x19, 0xd8,
	0xdc, 0xf7, 0xc6, 0xe1, 0x74, 0x1f, 0x87, 0x17, 0x47, 0x24, 0xbe, 0xf4, 0x3d, 0xb2, 0x1b, 0xc5,
	0x34, 0xa5, 0xe8, 0x96, 0x8d, 0x8f, 0xee, 0x9f, 0x51, 0x7a, 0x16, 0x90, 0xa7, 0x7c, 0xfe, 0x24,
	0x3b, 0x7d, 0x9a, 0xfa, 0x33, 0x92, 0xa4, 0x78, 0x16, 0x89, 0x25, 0xce, 0x57, 0x2d, 0xd8, 0xca,
	0x57, 0x1d, 0xe2, 0xf9, 0x8b, 0x78, 0x4a, 0xe2, 0xb1, 0x97, 0xfa, 0x34, 0x74, 0xc9, 0xaf, 0x33,
	0x92, 0xa4, 0x68, 0x0c, 0xab, 0x91, 0x9c, 0x18, 0xb6, 0xb6, 0x5b, 0x8f, 0x06, 0x7b, 0x0f, 0x77,
	0x4b, 0x02, 0xbc, 0x8c, 0x02, 0x8a, 0xa7, 0x07, 0xe7, 0xd8, 0x0f, 0x15, 0x17, 0x37, 0x5f, 0x86,
	0x7e, 0x0c, 0x83, 0x13, 0x1c, 0x5e, 0x48, 0x8e, 0xc3, 0x15, 0xce, 0xe5, 0x5e, 0x99, 0xcb, 0x7e,
	0x41, 0xe4, 0xea, 0x2b, 0x9c, 0xbf, 0xb6, 0xe0, 0x7e, 0x4e, 0xfd, 0x0c, 0x7b, 0x29, 0x8d, 0xfd,
	0xf0, 0xcc, 0x94, 0xf3, 0x08, 0x36, 0x4e, 0xd5, 0x8c, 0x2e, 0xed, 0x93, 0xa5, 0xd2, 0x3e, 0x33,
	0x96, 0xb8, 0x16, 0x8b, 0xaf, 0x2f, 0xf9, 0x9f, 0x5a, 0xf0, 0xa0, 0x2c, 0xb9, 0x4b, 0x22, 0x3c,
	0xb7, 0xd5, 0xdc, 0x89, 0x19, 0xfa, 0x3a, 0x52, 0x8b, 0x95, 0x5f, 0x5f, 0xd8, 0x3f, 0xb6, 0xe0,
	0x4e, 0x4e, 0xad, 0xc4, 0x4b, 0x22, 0xf4, 0x31, 0xc0, 0x89, 0xc7, 0xbe, 0x68, 0x98, 0x10, 0x29,
	0xe0, 0x3b, 0x15, 0x7c, 0x73, 0x1a, 0x57, 0xa3, 0x47, 0xfb, 0xb0, 0x26, 0x36, 0x91, 0xeb, 0x85,
	0x5c, 0x5b, 0x8b, 0xe4, 0x92, 0x1c, 0x8c, 0x35, 0xce, 0xa7, 0x30, 0xd0, 0xa4, 0x46, 0x08, 0x6e,
	0x9c, 0x13, 0x3c, 0xe5, 0xa2, 0xf4, 0x5d, 0xfe, 0xcd, 0xb0, 0x13, 0x3a, 0x9d, 0x73, 0xf6, 0x7d,
	0x97, 0x7f, 0xa3, 0x11, 0xac, 0x9e, 0x66, 0x21, 0x3f, 0xc8, 0xb0, 0xcd, 0xf1, 0x7c, 0xec, 0x38,
	0xb0, 0xa6, 0x6f, 0x98, 0xaf, 0x6f, 0x15, 0xeb, 0x9d, 0x6d, 0x80, 0xe2, 0x50, 0x7c, 0x57, 0x9c,
	0x9c, 0xe7, 0xbb, 0xe2, 0xe4, 0xdc, 0x79, 0x17, 0x06, 0x05, 0x45, 0xa2, 0x91, 0xb4, 0x73, 0x92,
	0x2f, 0x61, 0xe3, 0x80, 0xce, 0x66, 0x42, 0x97, 0x9c, 0xd1, 0x87, 0xd0, 0xe3, 0xa7, 0x4b, 0x22,
	0xa9, 0xcc, 0x3a, 0x65, 0x28, 0x72, 0xb4, 0x07, 0x9d, 0x13, 0x8f, 0xad, 0x5b, 0xd9, 0x6e, 0xd7,
	0x1a, 0x41, 0x90, 0x3a, 0x23, 0x18, 0x96, 0xae, 0x78, 0x22, 0xac, 0xeb, 0xfc, 0xb9, 0x25, 0x14,
	0x3b, 0xf6, 0x3c, 0x9a, 0x85, 0x29, 0xda, 0x84, 0xae, 0x87, 0xe3, 0xe9, 0x84, 0xca, 0x43, 0xca,
	0x11, 0xda, 0x86, 0x01, 0x16, 0x24, 0xc7, 0xf3, 0x88, 0x48, 0x1d, 0xeb, 0x10, 0x57, 0x1f, 0x0e,
	0x2f, 0xa4, 0x9a, 0xf9, 0x37, 0xe3, 0x96, 0x52, 0xff, 0xe4, 0x22, 0x1c, 0xde, 0x10, 0xdc, 0xc4,
	0x08, 0xbd, 0x03, 0x7d, 0xc6, 0xf7, 0xc5, 0xab, 0x90, 0xc4, 0xc3, 0x0e, 0x9f, 0x2a, 0x00, 0xb6,
	0xd7, 0x25, 0x0e, 0xfc, 0xe9, 0x51, 0x8a, 0xd3, 0x2c, 0x19, 0x76, 0xc5, 0x5e, 0x1a, 0xe4, 0xfc,
	0xbb, 0x05, 0x37, 0xb5, 0xdb, 0xc0, 0xf7, 0x1f, 0xc1, 0x6a, 0x80, 0x93, 0xf4, 0xa7, 0x85, 0x81,
	0xf2, 0x31, 0xda, 0x02, 0xc8, 0x38, 0xf9, 0x84, 0x4e, 0x95, 0xf0, 0x1a, 0x82, 0x1c, 0x58, 0x13,
	0x23, 0x12, 0x4f, 0xf0, 0x8c, 0xc8, 0x33, 0x18, 0x98, 0x4e, 0xe3, 0xd2, 0x80, 0xc8, 0x13, 0x19,
	0x18, 0x7a, 0x0c, 0xb7, 0xf4, 0x31, 0xe7, 0x25, 0x8e, 0x57, 0xc2, 0xd1, 0x23, 0xb8, 0xa9, 0x30,
	0xa9, 0x7c, 0x79, 0x52, 0x1b, 0x76, 0x1e, 0xc3, 0xaa, 0x32, 0x1b, 0x3b, 0x49, 0x72, 0xee, 0x47,
	0x33, 0x12, 0xa6, 0xb9, 0x8d, 0x34, 0xc4, 0xf9, 0x47, 0x1b, 0x90, 0xa6, 0x99, 0x03, 0x3a, 0x8b,
	0x70, 0x38, 0x47, 0x3f, 0x53, 0x9b, 0xe5, 0xfa, 0x92, 0x8e, 0xf7, 0xee, 0xd2, 0x30, 0xc3, 0x08,
	0x5d, 0x7b, 0x25, 0xb3, 0x8f, 0x27, 0xf8, 0xf2, 0x03, 0x4a, 0x5f, 0xd0, 0x20, 0x8d, 0xe2, 0x80,
	0x29, 0xbc, 0x6d, 0x50, 0x30, 0x88, 0x51, 0xcc, 0x70, 0x88, 0xcf, 0xa4, 0xc2, 0x85, 0x32, 0x75,
	0x88, 0xe9, 0x5b, 0x0e, 0x0f, 0xcf, 0x69, 0xa8, 0xf4, 0x68, 0x60, 0x68, 0x08, 0xbd, 0x99, 0x7f,
	0xc2, 0xf7, 0x10, 0xba, 0x53, 0x43, 0xb6, 0xda, 0x8b, 0xc9, 0xd4, 0x4f, 0xc7, 0x33, 0xae, 0xda,
	0xde, 0x76, 0xeb, 0x51, 0xdb, 0x35, 0x30, 0xf4, 0x3e, 0xf4, 0x92, 0x14, 0xc7, 0xe9, 0x38, 0x1d,
	0xae, 0x72, 0x65, 0x8c, 0x76, 0x45, 0xba, 0xdc, 0x55, 0xe9, 0x72, 0xf7, 0x58, 0xa5, 0x4b, 0x57,
	0x91, 0xa2, 0xf7, 0xa0, 0x43, 0xc2, 0xe9, 0x38, 0x1d, 0xf6, 0x6b, 0xd7, 0x08, 0x42, 0x15, 0x96,
	0x95, 0x95, 0x61, 0x59, 0x58, 0x96, 0x44, 0xae, 0xbe, 0xc2, 0x09, 0xe0, 0xad, 0x92, 0x4d, 0x7d,
	0x92, 0xa0, 0x63, 0x40, 0x59, 0xc9, 0xd6, 0x3c, 0xf4, 0x0c, 0xf6, 0x1e, 0x2c, 0x35, 0xac, 0xa4,
	0x75, 0x2b, 0xd6, 0x3b, 0xff, 0x5c, 0x81, 0xdb, 0x06, 0x69, 0x78, 0xea, 0x9f, 0x5d, 0xaf, 0x07,
	0xdd, 0x82, 0xf6, 0x05, 0x51, 0x91, 0x9a, 0x7d, 0x32, 0x4b, 0xa6, 0xf3, 0x88, 0xbc, 0x08, 0x95,
	0xb7, 0xa8, 0xa1, 0x9a, 0x39, 0x7e, 0x45, 0xa5, 0x97, 0xa8, 0x21, 0x8b, 0x22, 0xfc, 0xf3, 0x3c,
	0x26, 0xca, 0x3d, 0x0a, 0x00, 0xbd, 0x05, 0x9d, 0x4b, 0x1c, 0x64, 0xca, 0x33, 0xc4, 0x40, 0xb7,
	0x79, 0xef, 0x35, 0x6c, 0xbe, 0xda, 0xd4, 0xe6, 0x43, 0xe8, 0x91, 0x2f, 0xa2, 0x00, 0xfb, 0x21,
	0xf7, 0x93, 0xbe, 0xab, 0x86, 0xce, 0x99, 0x75, 0x41, 0x99, 0x76, 0x13, 0xf4, 0x29, 0xdc, 0xce,
	0x6c, 0x54, 0x5a, 0xf2, 0xdb, 0x35, 0x96, 0x64, 0xa4, 0x6e, 0x79, 0xb5, 0xf3, 0xaf, 0x36, 0xdc,
	0x31, 0x09, 0xd3, 0x18, 0x7b, 0xe9, 0xf5, 0x5a, 0x72, 0x0b, 0xc0, 0x93, 0x8c, 0x27, 0x54, 0x45,
	0xd6, 0x02, 0x41, 0x0f, 0x60, 0x3d, 0x25, 0xe1, 0x94, 0xc4, 0xca, 0x3b, 0x85, 0x75, 0x4d, 0x90,
	0xdf, 0x75, 0x32, 0xf5, 0x3d, 0x3f, 0x24, 0xfc, 0x32, 0xcb, 0xd8, 0xaa, 0x63, 0x8c, 0x93, 0x1a,
	0x1f, 0x72, 0x22, 0x61, 0x71, 0x13, 0xb4, 0x23, 0x4f, 0xb7, 0x1c, 0x79, 0xb4, 0x98, 0xd1, 0x33,
	0x63, 0x86, 0xbe, 0x43, 0xec, 0x7b, 0x84, 0x5b, 0xbb, 0xed, 0x9a, 0x20, 0xdb, 0x21, 0xa5, 0x29,
	0x0e, 0x64, 0x60, 0xe9, 0x73, 0x1a, 0x1d, 0xd2, 0x7d, 0x0c, 0x5e, 0xc3, 0xc7, 0x06, 0x0d, 0x7d,
	0xcc, 0xa1, 0x56, 0x58, 0x10, 0x4a, 0x4f, 0xd0, 0x67, 0x70, 0x27, 0x2b, 0xe3, 0xd2, 0x9b, 0x1e,
	0xd6, 0x79, 0x13, 0x27, 0x76, 0xab, 0x38, 0x38, 0xbf, 0x5f, 0x81, 0xbb, 0x15, 0xc4, 0xcf, 0xfd,
	0xff, 0xaf, 0x4f, 0x6d, 0x42, 0x77, 0xe6, 0x6b, 0x89, 0x45, 0x8e, 0xd0, 0x0e, 0x6c, 0x28, 0x53,
	0x49, 0xe3, 0xdc, 0xe0, 0xc6, 0xb1, 0x50, 0xe1, 0x23, 0x52, 0xf4, 0xe9, 0x0f, 0xa5, 0x1f, 0xe9,
	0x90, 0x4e, 0xf1, 0x32, 0x0e, 0x0a, 0x2f, 0xca, 0x21, 0xe7, 0x15, 0x6c, 0x56, 0x6a, 0x22, 0x41,
	0xbf, 0x80, 0xbb, 0x59, 0xd5, 0x8c, 0xd4, 0xff, 0x77, 0x1a, 0xe9, 0xff, 0xb9, 0xef, 0x56, 0x73,
	0x71, 0xbe, 0xea, 0xc0, 0xdb, 0x0b, 0x1b, 0x81, 0xeb, 0xb5, 0xc3, 0x87, 0xd0, 0x57, 0x1d, 0x5c,
	0x22, 0xeb, 0xcd, 0x51, 0x99, 0x4d, 0xde, 0xee, 0x15, 0xc4, 0x0d, 0xf2, 0xff, 0x8e, 0xd6, 0xac,
	0x3d, 0xa7, 0x21, 0x99, 0x2b, 0x5b, 0x99, 0x28, 0xab, 0xa8, 0xcc, 0x8e, 0x6c, 0x42, 0x55, 0x45,
	0x65, 0xe3, 0x4c, 0x5e, 0x1c, 0x45, 0xc1, 0xfc, 0x27, 0x38, 0x15, 0x37, 0x7f, 0xf9, 0x2d, 0x2a,
	0x88, 0xd9, 0x8d, 0xe5, 0x83, 0x66, 0x59, 0x41, 0x92, 0xa2, 0x1f, 0x01, 0xc4, 0xe4, 0x34, 0x0b,
	0xa7, 0x7c, 0xc3, 0xfa, 0xd4, 0xa0, 0x51, 0xb3, 0xea, 0x2f, 0x97, 0x9f, 0x69, 0x73, 0x42, 0x65,
	0x9e, 0xb0, 0x61, 0xb4, 0x0b, 0x08, 0x7b, 0x69, 0x86, 0x03, 0x97, 0x78, 0xc4, 0xbf, 0x24, 0x42,
	0x5b, 0xc0, 0xb5, 0x55, 0x31, 0x63, 0x70, 0x96, 0x15, 0xf4, 0xc0, 0xe2, 0x2c, 0x60, 0xf4, 0x01,
	0xac, 0x0a, 0x89, 0xc6, 0xe9, 0x70, 0xad, 0x56, 0xfa, 0x9c, 0x96, 0x45, 0x6b, 0xf1, 0x2d, 0xd9,
	0xaf, 0x8b, 0x68, 0xad, 0x63, 0xce, 0xef, 0x5a, 0x30, 0x5a, 0xe8, 0xa6, 0x09, 0xf2, 0xe1, 0xed,
	0x6c, 0xd1, 0xac, 0xbc, 0x28, 0x57, 0x6a, 0x80, 0x17, 0x73, 0x73, 0xfe, 0x6e, 0xa6, 0xc1, 0xe7,
	0x32, 0x16, 0x5c, 0xef, 0x55, 0xd1, 0x12, 0x98, 0x56, 0x13, 0x1b, 0x58, 0x29, 0xc9, 0xb5, 0x9b,
	0x24, 0xb9, 0x1b, 0x55, 0x49, 0xee, 0x7d, 0xb8, 0xab, 0x80, 0xa3, 0x88, 0x78, 0xfe, 0xa9, 0xef,
	0x61, 0xde, 0xe2, 0x8a, 0x9b, 0x51, 0x3d, 0xa9, 0xef, 0xff, 0x8c, 0xc6, 0x33, 0x19, 0xd5, 0x0c,
	0x8c, 0x39, 0x4f, 0xbe, 0x15, 0xf6, 0x2e, 0xf0, 0x99, 0x4a, 0x92, 0x36, 0xac, 0x73, 0x7b, 0x19,
	0xfa, 0xa2, 0x32, 0xd2, 0xb8, 0x31, 0x8c, 0x9d, 0xc6, 0xc3, 0x81, 0x97, 0x05, 0x38, 0x25, 0x2e,
	0xbb, 0x23, 0x22, 0x59, 0x9a, 0xa0, 0x2c, 0xf4, 0x33, 0xe6, 0x9d, 0x59, 0x4c, 0x62, 0xee, 0xda,
	0xa2, 0xd0, 0xcf, 0x31, 0x2b, 0xd5, 0x29, 0x1b, 0xda, 0xa9, 0x4e, 0xe1, 0x8d, 0x52, 0x9d, 0x22,
	0x76, 0xab, 0x38, 0x38, 0x7f, 0x69, 0xc3, 0xba, 0x4e, 0x7c, 0xcd, 0x29, 0x4e, 0x2b, 0x42, 0x56,
	0xcc, 0x22, 0x84, 0x27, 0x37, 0xad, 0x09, 0x95, 0x23, 0x2d, 0xe9, 0xdd, 0x30, 0x92, 0x1e, 0xc7,
	0xb9, 0x34, 0x1d, 0x85, 0xab, 0x26, 0x4d, 0x6f, 0xb0, 0xba, 0xf5, 0x0d, 0x56, 0xaf, 0xa2, 0xc1,
	0x72, 0x60, 0x2d, 0xf0, 0x67, 0x7e, 0xba, 0x8f, 0x03, 0x1c, 0xe6, 0x15, 0x91, 0x81, 0xa1, 0x4f,
	0x60, 0x23, 0x61, 0x8e, 0x86, 0x03, 0xd5, 0xe1, 0xf4, 0x9b, 0x74, 0x38, 0xd6, 0x22, 0x74, 0x00,
	0xeb, 0x21, 0x8d, 0x67, 0x05, 0x97, 0x46, 0x7d, 0x92, 0xb9, 0xc6, 0xf9, 0x0c, 0x36, 0x0c, 0xab,
	0x25, 0xe8, 0x13, 0x58, 0xd7, 0xed, 0xab, 0xd2, 0xf0, 0xfd, 0xe5, 0xbe, 0xe1, 0xbb, 0xe6, 0x2a,
	0xe7, 0x0f, 0x66, 0x14, 0xc9, 0xfb, 0xf1, 0xeb, 0x2e, 0x7c, 0xb4, 0xe6, 0x7e, 0xc5, 0x6e, 0xee,
	0x99, 0x4d, 0x29, 0x7f, 0x9f, 0x15, 0xd5, 0x4d, 0x5b, 0x94, 0x9e, 0x1a, 0xb4, 0xd0, 0x4b, 0xac,
	0x84, 0xdc, 0x29, 0x27, 0xe4, 0x2d, 0x00, 0x9a, 0xa5, 0xc7, 0x31, 0x9e, 0x92, 0x09, 0x95, 0xee,
	0xa2, 0x21, 0xcc, 0x63, 0x23, 0x3c, 0xe7, 0x07, 0x94, 0x65, 0xb3, 0x1c, 0xb2, 0xc2, 0x35, 0xc2,
	0xf3, 0x66, 0xcd, 0x11, 0x27, 0x64, 0x8d, 0x5b, 0x84, 0xe7, 0x32, 0x7b, 0x88, 0xb4, 0x57, 0x00,
	0x55, 0x09, 0x0c, 0x2a, 0x13, 0x98, 0x15, 0x15, 0xf2, 0xa7, 0x2d, 0x2b, 0x2a, 0x1c, 0x16, 0x8f,
	0xd7, 0xed, 0xe6, 0x8f, 0xd7, 0x55, 0x1c, 0x9c, 0xff, 0x98, 0x5e, 0x70, 0x24, 0x4d, 0x73, 0xbd,
	0x5e, 0xc0, 0xda, 0xda, 0x48, 0xd5, 0x3a, 0x2b, 0xb2, 0xad, 0x55, 0x00, 0xb3, 0x03, 0x95, 0x73,
	0xb2, 0x51, 0x96, 0x43, 0xfe, 0xd8, 0x16, 0xe9, 0xb6, 0x17, 0x23, 0x3d, 0xd6, 0x74, 0xcc, 0x58,
	0xb3, 0x03, 0x1b, 0xca, 0xbb, 0xa4, 0x4b, 0x75, 0x45, 0x11, 0x66, 0xa2, 0xb6, 0xdf, 0xf5, 0xca,
	0x7e, 0x67, 0x96, 0xec, 0xab, 0x4b, 0x4a, 0xf6, 0xbe, 0xe1, 0x97, 0x76, 0x4e, 0x84, 0x26, 0x39,
	0x71, 0xd0, 0xa0, 0xf1, 0x5b, 0x2b, 0x7b, 0xf8, 0x1e, 0x74, 0x93, 0x79, 0xe8, 0x8d, 0x53, 0x5e,
	0xb0, 0x2c, 0x77, 0x54, 0x49, 0x69, 0x79, 0x98, 0xb2, 0xb7, 0xed, 0x61, 0x0a, 0x6f, 0xe4, 0x61,
	0x8a, 0xd8, 0xad, 0xe2, 0xe0, 0xfc, 0xad, 0x0b, 0xc3, 0x0a, 0xe2, 0x37, 0x10, 0x6c, 0x3e, 0x82,
	0x4e, 0x14, 0xe0, 0x50, 0x55, 0xf6, 0x0d, 0x85, 0x16, 0x6b, 0xac, 0x48, 0xd5, 0x2e, 0x45, 0xaa,
	0x2d, 0x00, 0x3f, 0xbc, 0xa4, 0xbe, 0x47, 0x58, 0x87, 0x25, 0xfc, 0x51, 0x43, 0xb4, 0x79, 0xd6,
	0x5f, 0x75, 0x8c, 0xf9, 0x97, 0x71, 0xc0, 0xac, 0x29, 0x47, 0xfc, 0x94, 0x32, 0x7b, 0x69, 0x10,
	0xf3, 0x1c, 0x35, 0x64, 0xad, 0xb7, 0x7a, 0xe0, 0xd3, 0x31, 0x6d, 0x97, 0x63, 0xfc, 0x85, 0xcc,
	0x5d, 0x1a, 0xc2, 0x9a, 0x0b, 0x39, 0x3a, 0x38, 0x27, 0xde, 0x85, 0xe6, 0x9f, 0x25, 0x9c, 0xdd,
	0x4a, 0x89, 0x4d, 0xa8, 0x74, 0xd3, 0x02, 0xd0, 0xe4, 0xd5, 0x3c, 0x54, 0x87, 0xd0, 0xc7, 0x39,
	0x05, 0xef, 0x16, 0xea, 0xeb, 0x6d, 0x9d, 0x9c, 0xb5, 0x36, 0x09, 0x09, 0xa7, 0x2f, 0xb2, 0xb4,
	0x91, 0xfb, 0x16, 0xc4, 0x4c, 0x4f, 0xca, 0x2e, 0x5c, 0xb4, 0x0d, 0x71, 0xc3, 0x74, 0x8c, 0x45,
	0xdc, 0x62, 0x2c, 0x9e, 0x69, 0x6e, 0x8a, 0x88, 0x6b, 0xc1, 0x7a, 0xc4, 0x90, 0xa1, 0xf9, 0x16,
	0x27, 0xb4, 0x50, 0x26, 0x6f, 0x2c, 0x9a, 0x92, 0x71, 0x3a, 0xbc, 0x5d, 0x2f, 0x6f, 0x4e, 0xcc,
	0x56, 0x7a, 0x34, 0x3c, 0xf5, 0xe3, 0xd9, 0x38, 0x1d, 0xa2, 0xfa, 0x95, 0x39, 0xb1, 0xf3, 0xdb,
	0x96, 0xd1, 0x19, 0x1b, 0x57, 0x27, 0x41, 0xa7, 0x30, 0xcc, 0x16, 0x4c, 0xca, 0x6b, 0xfb, 0xb8,
	0xd1, 0x0d, 0x10, 0xd9, 0x61, 0x21, 0xaf, 0xbd, 0xff, 0x0e, 0xa0, 0xf4, 0x33, 0x2c, 0xfa, 0x39,
	0xdc, 0xdc, 0xf7, 0x24, 0x33, 0xf9, 0xe0, 0xf7, 0xa0, 0xc1, 0xab, 0x5e, 0x32, 0xba, 0xb7, 0xec,
	0xf7, 0x9d, 0x04, 0x7d, 0x0e, 0xb7, 0x0b, 0xbe, 0xea, 0x55, 0x78, 0xa7, 0xc1, 0xcb, 0xaf, 0x4f,
	0x6a, 0x79, 0x4f, 0x60, 0xa0, 0x78, 0xb3, 0x3a, 0x6a, 0xbb, 0xa6, 0x60, 0xba, 0x9a, 0xac, 0xea,
	0xa9, 0x6a, 0xa7, 0xd1, 0x6b, 0x48, 0x2d, 0xef, 0x5f, 0xc2, 0x1d, 0x9b, 0x37, 0x93, 0xf9, 0x51,
	0xc3, 0xb7, 0x96, 0xab, 0xc8, 0x5e, 0xe4, 0x80, 0x9d, 0x46, 0xfe, 0x52, 0xcb, 0x7b, 0x0a, 0x9b,
	0x36, 0x6f, 0xe9, 0xb2, 0x4f, 0x9a, 0x3b, 0xe4, 0x55, 0x4e, 0x50, 0xd4, 0x49, 0x3b, 0x8d, 0x4a,
	0xa1, 0x5a, 0xde, 0x31, 0x7c, 0x73, 0xc1, 0x5f, 0x08, 0xd0, 0x7b, 0x55, 0x2b, 0x97, 0xfd, 0xdb,
	0x60, 0xf4, 0x70, 0xc9, 0x0a, 0xed, 0x17, 0xe9, 0xdf, 0x68, 0x7f, 0x5b, 0xb0, 0x1e, 0x17, 0xe4,
	0xd6, 0xdf, 0x5f, 0xc2, 0xa8, 0xfa, 0x1f, 0x04, 0x4d, 0xf7, 0xfe, 0x12, 0xee, 0x2d, 0xfd, 0x45,
	0x1f, 0x7d, 0xd0, 0x64, 0xeb, 0xf2, 0x5f, 0x00, 0x9a, 0xee, 0xff, 0x2b, 0xe6, 0x31, 0xcf, 0x68,
	0xec, 0x91, 0x37, 0xe4, 0x92, 0x3e, 0x7c, 0xab, 0x72, 0x83, 0x37, 0xe0, 0x97, 0xf6, 0x59, 0xae,
	0xdd, 0x39, 0x89, 0xb5, 0x41, 0xae, 0x7f, 0xf4, 0xbd, 0x2b, 0x3c, 0x30, 0xd5, 0x6d, 0xb3, 0xff,
	0xe4, 0xf3, 0xef, 0x26, 0x02, 0x7e, 0x6a, 0xd3, 0x7d, 0x64, 0x03, 0x87, 0xdf, 0x38, 0xe9, 0xf2,
	0x54, 0xf6, 0x83, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xab, 0x8e, 0x7a, 0x5a, 0xca, 0x23, 0x00,
	0x00,
}
